@startuml er

' hide the spot
hide circle

' avoid problems with angled crows feet
' skinparam linetype ortho

entity "User" {
    ID : number
    name : string
    bio : string
    email : Email
    password : string
}

entity "Task" {
    ID : number
    name : string
    description : string
    isPrivate : boolean
}

entity "UserTask" {
    ID : number
    start-time : Date
    end-time : Date

    --
    userID : number
    taskID : number
}

entity "Tag"{
    ID : number
    name : string

}

entity "TaskTag"{
    ID : number
    --
    taskID : number
    tagID : number
}

UserTask ||..o{ User
UserTask ||..o{ Task

TaskTag ||..o{ Task
TaskTag ||..o{ Tag 
@enduml
